### ISSUE TITLE
Login failure.

### ISSUE THREAD

**Issue by alatteri** [twilio/OpenVBX-iPhone#1]
running OpenVBX .90 on Webfaction with https.
iPhone app v.1.0.2

whenever I try to login to iPhone app, always gives me Login Failed.  Your email address or password is invalid.

checked many times, i am entering it correctly, and web-based works fine.

**Comment by minddog** [comment]
Hey, there is an issue on some webhosts where the Authorization headers get lost inside php runtime.  It does not pass through the correct headers for basic authentication and has to be fixed via mod rewrite or alternatives with other webservers.  There is work to fix this for dreamhost and godaddy with the mod rewrite rules in the .htaccess distributed with OpenVBX 0.90 and higher.  This isn't an issue with the iPhone app, but with OpenVBX running on webfaction.  Can you contact webfaction for more details on how to get authorization headers passed into the php application?

**Comment by alatteri** [comment]
here is what I got back from WebFaction support:

"We need more details. What headers exactly? What URL is the access happening on? Is it a GET or POST? Can we re-produce the issue? We need exact technical details to be able to determine what we would need to change. Please let us know if you have any more questions."

**Comment by L2G** [comment]
I ran into trouble logging in with the iPhone app using a password of mixed letters, digits, and punctuation. But after some quick troubleshooting I discovered that having a colon (:) in the password was the problem. If I changed my password to delete the colon and then tried logging in from the iPhone app, it worked.
