### ISSUE TITLE
Twilio Client

### ISSUE THREAD

**Issue by iAnomaly** [twilio/OpenVBX-iPhone#2]
Would it be possible to get Twilio Client support on the iPhone app? I.e. VoIP via cell/wireless connection versus using the device's number? This would allow non-phone iOS devices to be supported as well (iPad, iPod Touch, etc).

**Comment by Gipetto** [comment]
Twilio client support is in beta for iOS at this time and we're planning an update to the iPhone app. Unfortunately we don't have an release date as of yet.

Shawn

**Comment by iAnomaly** [comment]
Outstanding, thanks for the update.
